apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: flocket
data:
  kong.conf: |
    database = postgres
    pg_host = postgres
    pg_port = 5432
    pg_user = kong
    pg_database = kong
    pg_password = flocket
    admin_listen = 0.0.0.0:8001, 0.0.0.0:8444 ssl
    proxy_listen = 0.0.0.0:8000, 0.0.0.0:8443 ssl
    status_listen = 0.0.0.0:8100
    log_level = debug
    proxy_access_log = /dev/stdout
    admin_access_log = /dev/stdout
    proxy_error_log = /dev/stderr
    admin_error_log = /dev/stderr
    ssl_cert = /etc/kong/certs/tls.crt
    ssl_cert_key = /etc/kong/certs/tls.key
    plugins = bundled,jwt,rate-limiting,http-log,prometheus,cors,request-transformer,response-transformer,ip-restriction,proxy-cache
    nginx_worker_processes = auto
    proxy_cache = on
    proxy_cache_response_codes = 200 301 302 404
    proxy_cache_timeout = 30s
    proxy_cache_storage_size = 128m
    nginx_http_proxy_cache_path = /tmp/cache levels=1:2 keys_zone=cache:10m max_size=128m inactive=60m 