apiVersion: v1
kind: Secret
metadata:
  name: kong-tls
  namespace: flocket
type: kubernetes.io/tls
data:
  tls.crt: ${KONG_CERT_BASE64}
  tls.key: ${KONG_KEY_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: kong-postgres
  namespace: flocket
type: Opaque
data:
  password: ${POSTGRES_PASSWORD_BASE64} 