_format_version: "2.1"
services:
  - name: auth-service
    url: http://auth-service:3000
    routes:
      - name: auth-routes
        paths:
          - /auth
        strip_path: true
        preserve_host: true

  - name: users-service
    url: http://users-service:3001
    routes:
      - name: users-routes
        paths:
          - /users
        strip_path: true
        preserve_host: true

  - name: circles-service
    url: http://circles-service:3002
    routes:
      - name: circles-routes
        paths:
          - /circles
        strip_path: true
        preserve_host: true

  - name: spheres-service
    url: http://spheres-service:3003
    routes:
      - name: spheres-routes
        paths:
          - /spheres
        strip_path: true
        preserve_host: true

  - name: messaging-service
    url: http://messaging-service:3004
    routes:
      - name: messaging-routes
        paths:
          - /messaging
        strip_path: true
        preserve_host: true

  - name: notifications-service
    url: http://notifications-service:3005
    routes:
      - name: notifications-routes
        paths:
          - /notifications
        strip_path: true
        preserve_host: true

  - name: wellbeing-service
    url: http://wellbeing-service:3006
    routes:
      - name: wellbeing-routes
        paths:
          - /wellbeing
        strip_path: true
        preserve_host: true

  - name: search-service
    url: http://search-service:3007
    routes:
      - name: search-routes
        paths:
          - /search
        strip_path: true
        preserve_host: true 